// Generated by CoffeeScript 1.8.0
var MQTT_CLIENTID, MQTT_PWD, MQTT_USER, mqtt;

mqtt = require('mqtt');

MQTT_USER = "your MQTT username on ZADATA";

MQTT_PWD = "your MQTT password on ZADATA";

MQTT_CLIENTID = "some_client_id";

console.log("Loading event");

exports.handler = function(event, context) {
  var client;
  console.log("event =\n", event);
  client = mqtt.connect("mqtt://" + MQTT_USER + ":" + MQTT_PASS + "@mqtt.zadata.com:1883?clientId=" + MQTT_CLIENTID);
  console.log("after mqtt.connect()");
  client.publish(event.topic, event.value, {
    retain: (event.retain != null) && event.retain
  });
  console.log("after client.publish()");
  client.end();
  console.log("after client.end()");
  client.on("close", (function() {
    return context.done(null, "SUCCESS");
  }));
  client.on("error", (function() {
    return context.done(null, "ERROR");
  }));
};
